export default { 
    inviteWorking: require('../assets/images/inviteWorking.png'),
    pressinstitute: require('../assets/images/pressinstitute.png'),
    requireInfo: require('../assets/images/requireInfo.png'),
    provideinfo: require('../assets/images/provideinfo.png'),
    reflectinfo: require('../assets/images/reflectinfo.png'),
    worklist: require('../assets/images/worklist.png'),
    document: require('../assets/images/document.png'),
    agencyList: require('../assets/images/agencyList.png'),
    jounalistList: require('../assets/images/jounalistList.png'),
    bellhasnotif: require('../assets/images/bell.png'),
    bellnonotif: require('../assets/images/bellno.png'),
    calendar: require('../assets/images/calendar.png'),
    user: require('../assets/images/icons_user.png'),
    password: require('../assets/images/icons_password.png'),
    noImage: require('../assets/images/noImage.jpg'),
    noAvatar: require('../assets/images/noAvatar.png'),
    fileIcon: require('../assets/images/File.png'),
    splastBG: require('../assets/images/background.png'),
    press: require('../assets/images/press.png') ,
    annoucement: require('../assets/images/annoucement.png'),
    present: require('../assets/images/present.png'),
    presslogo: require('../assets/images/presslogo.jpg'),
}